### ISSUE TITLE
Cant open the ym file,whats wrong?

### ISSUE THREAD

**Issue by starock** [FlorentFlament/ym2149-streamer#1]
$python streamer.py /dev/cu.usbmodem1441 ~/documents/last.ym

Traceback (most recent call last):
  File "streamer.py", line 126, in <module>
    main()
  File "streamer.py", line 96, in main
    ym = YmReader(fd)
  File "streamer.py", line 62, in __init__
    self.__parse_header()
  File "streamer.py", line 42, in __parse_header
    'Unsupported file format: Digidrums are not supported')
Exception: Unsupported file format: Digidrums are not supported

.ym files form: http://pacidemo.planet-d.net/aldn/

**Comment by twentytwoo** [comment]
You need to extract the .ym files with lha

> Note that the files in the zip archives are compressed with lha (which can be installed through the Fedora lha package). Therefore, one has to uncompress the ym files before playing them with streamer.py.

`lha -e file.ym`, and then run the output .ym through the python script.

**Comment by taxilly** [comment]
You have to extract the .ym files with lha

>Note that the files in the zip archives are compressed with lha (which can be installed through the Fedora lha package). Therefore, one has to uncompress the ym files before playing them with streamer.py.

So `lha -e file.ym`, and then run the decompressed .ym files through the python script.

**Comment by simondotm** [comment]
Or, you might have a YM file that actually does contain digi-drum information that is so far unsupported. In which case, choose a different tune. Or take a look at the pull request from sebdel, which _looks_ like it adds a patch to support DD's.

**Comment by FlorentFlament** [comment]
Mmhh, pretty old comment (sorry for that).
Indeed, simondotm is right. Though I agree the error message is a bit 'raw': "Exception: Unsupported file format: Digidrums are not supported".
