### ISSUE TITLE
No audio output

### ISSUE THREAD

**Issue by taxilly** [FlorentFlament/ym2149-streamer#2]
My circuit works when using your ym2149-test repo code, playing the C scale.

Streaming the files to the IC results in no audio output, any suggestions?

**Comment by henrikeri** [comment]
Hi,
I seem to be having the exact same issue. When using the test repo code, the C scale plays perfectly. However, when using the streamer there is no sound, although it seems to be streaming. I am receiving data from the computer, and I can see the Arduino sending data to the YM2149 over the analog pins, but nothing appears to be transmitted over the digital pins (Except the clock).

Any help greatly appreciated!

**Comment by FlorentFlament** [comment]
Hi, bit late, but this may be a serial line configuration issue. I added the `serial-setup.sh` script, gently provided by sebdel
