### ISSUE TITLE
*Warning* End! marker not found after frames

### ISSUE THREAD

**Issue by HenryDane** [FlorentFlament/ym2149-streamer#3]
After setting everything up exactly as in your blog post, i used `lha -e somefile.ym` to decompress the file. 
The `lha` tool said 
`song_096.ym     - Melted   :  ooooooooooooooooooooooo`
so I assume everything works. The only problem is that I get 
`*Warning* End! marker not found after frames` 
from the `streamer.py` tool and then silence while nothing happens. Any help would be appreciated.

**Comment by FlorentFlament** [comment]
Sorry for the belated answer.
As far as I remember, some YM files are missing the "End!" tag, at the end of the song. If everything else is fine, the song should play anyway; this is only a warning message. If you don't get any sound, there's probably something else that is wrong.
